### ISSUE TITLE
New version 5.3.2 does not have the react 18 in peer dependency

### ISSUE THREAD

**Issue by shreyasvimal** [kriasoft/isomorphic-style-loader#213] opened 2024-08-08 14:31 UTC
When I install the version 5.3.2, it throws error for react version `^18.0.0`. The new version does not have the latest PR and is not supporting the react 18.

**Comment by adrien-febvay** [comment] 2024-09-09 16:04
Duplicate of https://github.com/kriasoft/isomorphic-style-loader/issues/205

**Comment by dazlious** [comment] 2024-12-04 17:24
https://github.com/kriasoft/isomorphic-style-loader/tree/v5.4.0

**Closed by dazlious** 2024-12-04 17:24 UTC
